version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the NLP...
      - pip install -r requirements.txt
#      - python application.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"